generalInformation:
  serviceAdminEmail: gentlekobby@gmail.com
  gheUsername: kobbyopoku
  billingAccount: test
  billingTeamName: test
  gheToken: ""
  adpAccessToken: ""
jira:
  adminToken: ""
  projectKey: test
  projectName: project-3
  leadUsername: kobbyopoku
  documentationUrl: "1"
projectInformation:
  projectName: project-3
  projectShortName: project-3
  buildType: maven
  testInstance: true
  preprodInstance: true
  uatInstance: true
cloudService:
  awsOrAzure: eks
  deploymentLocation: aws_ew3
automationService:
  jenkinsOrGithubActions: jenkins
  jenkinsAdmin: ""
  jenkinsDeveloper: ""
  jenkinsKubernetesAccess: ""
  kvUserOrGroupName: ""
  nexusKubernetesAccess: ""
gheOrganization:
  organizationName: kobbyopoku
  isNew: false
testingTools:
  sonarQube: false
  adminGroup: ""
  kubernetesAccess: ""
